In [1]:
import numpy as np

In [4]:
# dot-performs element wise multipliacation follwed by addition
array1 = np.array([1,2,3]) 
array2 = np.array([4,5,6])

np.dot(array1,array2)

32

In [9]:
# shape - gives the dimensions of a numpy array etc..
array3 = np.array([

      [
          [7,2,3],[3,7,6]
     ],
      [
          [1,2,9], [0,5,6]
     ],
     
])

array3.shape

(2, 2, 3)

In [17]:
# dtype: check datatype of a numpy array etc.. 
array3 = np.array([1,3,7,8.7,0])
array3.dtype
print(array3)


[1.  3.  7.  8.7 0. ]


In [25]:
# matmul / @ - performs matrix multiplication
matrix1 = np.array([[3,7,9],
                [3,6,7],
                [2,8,0]])
matrix2 = np.array([[2,8],
                [3,9],
                [2,5]])

multiplication = np.matmul(matrix1,matrix2)
print(matrix1 @ matrix2)
print(multiplication)

[[ 45 132]
 [ 38 113]
 [ 28  88]]
[[ 45 132]
 [ 38 113]
 [ 28  88]]


In [29]:
import urllib.request
urllib.request.urlretrieve(
    'https://www.stats.govt.nz/large-datasets/csv-files-for-download/'
,'businessData.txt')
businessData=np.genfromtxt('businessData.txt',delimiter=',',skip_header=1)

ValueError: Some errors were detected !
    Line #20 (got 5 columns instead of 1)
    Line #49 (got 5 columns instead of 1)
    Line #50 (got 3 columns instead of 1)
    Line #51 (got 2 columns instead of 1)
    Line #52 (got 2 columns instead of 1)
    Line #53 (got 5 columns instead of 1)
    Line #71 (got 3 columns instead of 1)
    Line #78 (got 712 columns instead of 1)
    Line #81 (got 106 columns instead of 1)
    Line #84 (got 31 columns instead of 1)

In [35]:
# add-it performs array broadcasting i.e.,add arrays of different sizes by managing the sizes of smaller array
import numpy as np

# Create a 2D array
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Create a 1D array
arr2 = np.array([10, 20, 30])

# Perform element-wise addition using broadcasting
result = arr1 + arr2

print(result)



[[11 22 33]
 [14 25 36]]


In [6]:
# array slicing
import numpy as np
arr = np.array([[[1,2,3],[2,6,8],[9,7,5]],
                [[2,8,9],[8,0,6],[3,6,8]]
                ])
print(arr[1:,1:2,0:3])

[[[8 0 6]]]


In [12]:
# creating zero, identity , random matrix
zero_matrix = np.zeros((3,5))
identity_matrix = np.ones((3,4))
random_matrix = np.random.rand(2,4)

print(zero_matrix)
print(identity_matrix)
print(random_matrix)
print(np.eye(2,4))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.41154902 0.01506383 0.89684902 0.20775013]
 [0.25554528 0.2352417  0.63986787 0.41193578]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [16]:
# linspace array
print(np.linspace(3,27 , 15))

[ 3.          4.71428571  6.42857143  8.14285714  9.85714286 11.57142857
 13.28571429 15.         16.71428571 18.42857143 20.14285714 21.85714286
 23.57142857 25.28571429 27.        ]


In [17]:
# os 
import os
os.getcwd()

'c:\\Users\\p mahaboob sana\\OneDrive\\Desktop\\python'